image: docker:latest

services:
  - docker:dind

variables:
  ECR_REPOSITORY_URI: public.ecr.aws/i0g1s5d6/reporting-service
  APP_NAME: reporting-service
  IMAGE_TAG: latest
  AWS_DEFAULT_REGION: $AWS_REGION


stages:
  - build and push

before_script:
  - apk add --no-cache python3 py3-pip
  - python3 -m venv venv
  - source venv/bin/activate
  - apk add aws-cli
  - aws --version

build and push:
  stage: build and push
  script:
    # These steps would be needed if you want to push to a private ECR repository, but for now we're using the public ECR.
    # Will be leaving them just to show how to do it.
    # - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    # - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    # - aws configure set region $AWS_REGION
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i0g1s5d6
    - docker build -t $APP_NAME .
    - docker tag $APP_NAME:latest $ECR_REPOSITORY_URI:latest
    - docker push $ECR_REPOSITORY_URI:latest
  only:
    - main