image: docker:latest

services:
  - docker:dind

variables:
  AWS_DEFAULT_REGION: eu-north-1
  ECR_REGISTRY: your-aws-account-id.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  ECR_REPOSITORY: your-repository-name
  IMAGE_TAG: $CI_COMMIT_SHA
  KUBE_NAMESPACE: your-kubernetes-namespace
  KUBE_DEPLOYMENT_NAME: your-deployment-name

stages:
  - build
  - push
  - deploy

before_script:
  - apk add --no-cache python3 py3-pip
  - pip3 install --upgrade awscli
  - aws --version
  - apk add --no-cache curl
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl

build:
  stage: build
  script:
    - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
  only:
    - main

push:
  stage: push
  script:
    - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY)
    - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name your-eks-cluster-name
    - kubectl set image deployment/$KUBE_DEPLOYMENT_NAME $KUBE_DEPLOYMENT_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -n $KUBE_NAMESPACE
  only:
    - main